### ISSUE TITLE
A problem about swGEMM (cblas_LINUX.a)

### ISSUE THREAD

**Issue by TianxiangLyu** [feifeibear/swGEMM#3]
I'm interested in your repository feifeibear/swGEMM
       Seems that there are a problem when I try to compile the swGEMM which shows that a library named "cblas_LINUX.a" are missed
       Recorded in cmakefile that the path is 
/home/export/online1/swyf/swdnn/fjr/201809/BLAS/swblas_release/thirdparty/lib/cblas_LINUX0324.a
/home/export/online1/swyf/swdnn/fjr/2018-09/BLAS/swblas_release/thirdparty/lib/libswblas0324.a
       
       These might be a path that can't be reached...
       I wonder how to compile the swGEMM next...

**Comment by feifeibear** [comment]
Cblas is compiled from source code http://www.netlib.org/blas/#_cblas.
swliblas0324 is a closed source blas library developed by CAS. You can ask for the lib from NSCCWX.
Actually, this project is a more efficient alternative for swblas. You may compile it without swblas.

**Comment by TianxiangLyu** [comment]
> Cblas is compiled from source code http://www.netlib.org/blas/#_cblas.
> swliblas0324 is a closed source blas library developed by CAS. You can ask for the lib from NSCCWX.
> Actually, this project is a more efficient alternative for swblas. You may compile it without swblas.

I have deleted the call from cblas, now it can be run
