### ISSUE TITLE
Some problem about ./gemm/dgemm.c

### ISSUE THREAD

**Issue by TianxiangLyu** [feifeibear/swGEMM#5]
When I change the API in sgemm_dma using the ldm compute function dgemmasm2 to dgemm in ./gemm/dgemm.c
the performance was lower than 0.25 Gflops... Seems that there must be something wrong...
I wonder where are the C source codes of the *.S in ./asm thought the assembly in ./asm have been rearranged by hand to fulfill the pipeline of ALU and BIU of SW26010 with double-launching as much as possible.
Sincerely want to learn from your codes and I'm now implementing A NoTrans B Trans.

**Comment by feifeibear** [comment]
Why not say it in Chinese if you could. I barely understand your sentence even with help of a Google translator.

**Comment by feifeibear** [comment]
Why not say it in Chinese if you could. I barely understand your sentence even with help of a Google translator.

**Comment by TianxiangLyu** [comment]
好的。。。
在sgemm_dma里面使用的ldm计算函数，我看到是用的dgemmasm2这个汇编S文件。。。
后来我是先看看dgemm的C语言源代码，于是就找到了./gemm/dgemm.c这里，但我在sgemm_dma里调用./gemm/dgemm.c里面的dgemm函数，性能非常差。。。大概只有0.25Gflops（使用./asm里面的汇编就算数据规模很小也能有300Gflops以上）
所以我是想找到dgemmasm2的C语言源代码，但我感觉好像./asm里面的汇编指令都重新调整过了，从而使得能够最大化双发射填满神威的计算和访存流水线。。。
我找了挺久的，除了./gemm文件下的几个，好像没有再找到其他从ldm计算的C语言文件
主要是我想深入研究这份代码，并且实现A NoTrans B Trans的计算

**Comment by feifeibear** [comment]
性能非常差是正常的，因为编译器能力很差，生成asm低效。
gemm里没有那应该就是没有的。

**Comment by TianxiangLyu** [comment]
好吧...那如果要实现transB的话，应该最好在gemm的外部trans了是吗...

**Comment by feifeibear** [comment]
据说，DMA有一种stride方式，可以在读入时候转置好。这种方式我试没有成功。
可以用寄存器通信方式实现高效矩阵转置，swcaffe应该实现过。

**Comment by TianxiangLyu** [comment]
感谢，那我参考下swcaffe的代码，在gemm外部实现转置
